<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leave Request</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; margin: 0; padding: 0; }
        .container { width: 100%; padding: 20px; }
        .header { text-align: center; font-size: 20px; font-weight: bold; color: #0056b3; margin-bottom: 20px; }
        .company-name { font-size: 18px; font-weight: bold; color: #2d3e50; margin-bottom: 10px; }
        .details { margin-top: 20px; padding: 10px; background-color: #f7f7f7; border-radius: 8px; }
        .details p { margin: 5px 0; font-size: 14px; }
        .footer { text-align: center; font-size: 12px; color: #aaa; margin-top: 20px; }

        /* Style for background image */
        .background {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
            opacity: 0.1;
        }

        .approved { background-color: #c8e6c9; color: #388e3c; }
        .rejected { background-color: #ffcdd2; color: #d32f2f; }
    </style>
</head>
<body>
    <div class="container">
        <div class="company-name"><?php echo e($leave->user->company); ?></div>
        <div class="date">
            DATE <?php echo e(\Carbon\Carbon::now()->format('d/m/Y')); ?>

        </div>
        <div class="header">Leave Request Details</div>
        <div class="<?php echo e($leave->status == 'approved' ? 'approved' : 'rejected'); ?>">
            <p><strong>Name:</strong> <?php echo e($leave->user->first_name); ?> <?php echo e($leave->user->last_name); ?></p>
            <p><strong>Start Date:</strong> <?php echo e($leave->start_date); ?></p>
            <p><strong>End Date:</strong> <?php echo e($leave->end_date); ?></p>
            
            <p><strong>Reason:</strong> <?php echo e(ucfirst(str_replace('_', ' ', $leave->reason))); ?></p>

            <!-- Conditionally display leave days based on reason -->
            <?php if($leave->reason == 'sick_leave'): ?>
                <p><strong>Effective Leave Days:</strong> <?php echo e($leave->effective_leave_days); ?></p>
            <?php else: ?>
                <p><strong>Leave Days Requested:</strong> <?php echo e($leave->leave_days_requested); ?></p>
            <?php endif; ?>
        </div>
    </div>

    <div class="footer">
        <p>Generated by Your <?php echo e($leave->user->company); ?></p>
        <p>Contact us: contact@yourcompany.com</p>
    </div>
</body>
</html>
<?php /**PATH C:\Users\MSI\OneDrive\Documents\GitHub\BackOfficee\resources\views/pdf/leave.blade.php ENDPATH**/ ?>